### ISSUE TITLE
Please Revive the TAG game option in CheckMate server. 

### ISSUE THREAD

**Issue by azispratama92** [matteoserva/YgoProServer#3]
I know that the TAG game is still accessible, but with the current system update, all new player are forced to join single game. 

I don't know if this caused by Percy launcher, but please we really loved your server, and the TAG game of yours. 

Many thanks Matteo =)

**Comment by matteoserva** [comment]
Hello, you can still choose the duel mode from the ygopro screen. Sadly many player weren't aware of that option and were unable to decide which mode to play. With the last update I changed the default settings so if you don't decide, then you'll enter the single duel. I haven't decided yet if it's better that way. If you really want to play a less common duel mode I would suggest you to use the other servers until I switch back to the old mode

**Comment by azispratama92** [comment]
That would be Good News =) ; btw some of my friends here Indonesia, Thailand, Malaysia, and Brazilia really missed your old TAG feature, i thought it was problem with the percy update, . I'm looking forward to the old switch, 

Once again many thanks Matteo =)

**Comment by azispratama92** [comment]
its been a while since i used, GNU/Linux distro as a daily driver, and i think its time for me to learn some programming, so glad that you make the ygopro server open source, i'll learn the code and make a full documentation for it, i hope someday i can revive the awesome checkmate server in the near future, thanks again =) 

have a good day.
